### ISSUE TITLE
Resize Tweet Card

### ISSUE THREAD

**Issue by elijahondiek** [ondiekelijah/MzalendoAlert#5]
The tweet card currently needs to fit better within the designated space. We need to adjust the dimensions and layout to ensure it displays correctly on all device sizes.

**Tasks:**

1. Review the current dimensions and layout of the tweet card.
2. Adjust the styling to make the tweet card responsive.
3. Test the tweet card on various screen sizes to ensure it looks good.

**Comment by OndiekOchieng** [comment]
Fantastic work, @munene-m 🎉 This PR #7 has addressed issue #5 with finesse.
